version: 2

models:
  - name: dim_breweries
    description: "Cleaned dimension table of all global breweries"
    columns:
      - name: brewery_id
        tests:
          - unique
          - not_null
      - name: brewery_type
        tests:
          - not_null