name: Deploy dbt Docs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-duckdb requests pandas

      - name: Run Python Data Ingestion
        run: |
          python ingest.py

      - name: Install dbt packages
        run: |
          dbt deps --profiles-dir

      - name: Generate dbt Documentation
        run: |
          dbt docs generate --target dev --profiles-dir

      - name: Deploy static docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target
          branch: gh-pages
          commit-message: "docs: Auto-update dbt documentation via GitHub Actions"